version: '3'
services:
  postgres:
    image: "postgres:latest"
    env_file:
      - ../config/postgres.env
    ports:
      - '5432:5432'
    expose:
      - '5432'

#  bamboo:
#    build:
#      context: ..
#      dockerfile: dockerfile
#    restart: on-failure
#    env_file:
#      - ../config/bamboo.env
#    depends_on:
#      - postgres
#    ports:
#      - 8198:8198